server:
  port: 88

opal:
  torrent:
    rss:
      cache.expire: 1800000 # 30ë¶„
      site:
        tf.url: http://www.tfreeca22.com
        th.url: https://torrenthaja.com
        tw.url: https://torrentwal.net




